name: followup
version: "0.0.1"
description: Contact tracking application
maintainer: Alex Babkin
stability: experimental
license: MIT

extra-source-files:
  - README.md
  - stack.yaml

dependencies:
  - base >= 4.8 && < 5
  - aeson >= 0.11.2.1
  - text
  - transformers
  - mtl
  - unordered-containers
  - lens
  - amazonka-s3
  - amazonka-dynamodb
  - conduit
  - conduit-extra
  - resourcet
  - heredoc

library:
  source-dirs:
    - src
  ghc-options: -Wall

executables:
  followup:
    main: Main.hs
    source-dirs: app
    dependencies:
      - base >= 4.8 && < 5
      - qmuli
    ghc-options: -Wall -static -threaded -rtsopts -with-rtsopts=-N

tests:
  tasty:
    main: Main.hs
    source-dirs:
      - tests
    dependencies:
      - base
      - qmuli
      - tasty
      - tasty-hspec

