name: followup
version: "0.0.1"
description: Contact tracking application
maintainer: Alex Babkin
stability: experimental
license: MIT

extra-source-files:
  - README.md
  - stack.yaml

dependencies:
  - base >= 4.8 && < 5
  - aeson >= 1.0 && < 1.1
  - text
  - transformers
  - mtl
  - unordered-containers
  - lens >= 4.14 && < 4.15
  - amazonka-dynamodb
  - heredoc
  - hashable
  - data-default >= 0.7 && < 0.8

library:
  source-dirs:
    - src
  ghc-options: -Wall

executables:
  followup:
    main: Main.hs
    source-dirs: app
    dependencies:
      - base >= 4.8 && < 5
      - qmuli
    ghc-options: -Wall -static -threaded -rtsopts -with-rtsopts=-N

tests:
  tasty:
    main: Main.hs
    source-dirs:
      - tests
    dependencies:
      - base
      - qmuli
      - tasty
      - tasty-hspec

